-- V7: no-op on Postgres. V6 already seeds the 70 demo players correctly here (the
-- original MySQL V6/V7 pair existed because V6 had a bug that V7 then cleaned up;
-- rewritten V6 folds in that fix directly). Kept as an empty file to preserve migration numbering.
